image: commonci-fil:latest
stages:
  - author
  - build
  - test

check_authors:
  stage: author
  script:
    - |
        test -s AUTHORS || (echo "ERREUR: Vous devez renseigner vos noms et prénoms dans le fichier AUTHORS"; exit 1)


    
build:
  stage: build
  script:
    - make
    - make -C tests
